# Generated by Django 3.0.3 on 2021-06-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='town_or_city',
        ),
    ]
