# Generated by Django 3.0.3 on 2021-06-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_town_or_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
